version: '3.7'
services:
    postgresql:
        container_name: postgres-db
        image: postgresdb-image
        build:
            context: .
            dockerfile: postgresdb.dockerfile
        volumes:
            - /var/db/data/postgresql:/var/lib/postgresql
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=admin
        ports:
            - '5432:5432'